language: objective-c

branches:
 only:
 - master

xcode_project: TaskQueue.xcodeproj
xcode_scheme: TaskQueue
osx_image: xcode8.3
xcode_sdk:
  - macosx
  - iphonesimulator
  - iphonesimulator9.0
  - appletvsimulator

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
- xcrun xctool -project TaskQueue.xcodeproj -scheme TaskQueue -sdk iphonesimulator run-tests
- xcrun xctool -project TaskQueue.xcodeproj -scheme TaskQueue -sdk macosx run-tests
- xcrun xctool -project TaskQueue.xcodeproj -scheme TaskQueue -sdk appletvsimulator run-tests
