language: swift

xcode_project: TaskQueue.xcodeproj
xcode_scheme: TaskQueue
osx_image: xcode12.2

script:
- set -o pipefail
- xcrun xcodebuild test -workspace TaskQueue.xcworkspace -scheme TaskQueue -destination 'arch=x86_64' | xcpretty
- xcrun xcodebuild test -workspace TaskQueue.xcworkspace -scheme TaskQueue -destination 'platform=iOS Simulator,name=iPhone 12' | xcpretty
- xcrun xcodebuild test -workspace TaskQueue.xcworkspace -scheme TaskQueue -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' | xcpretty
- xcrun xcodebuild test -workspace TaskQueue.xcworkspace -scheme TaskQueue -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty
- xcrun xcodebuild build -workspace TaskQueue.xcworkspace -scheme Cancellation -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' | xcpretty
